feat: реализованы функциональности пользователя и вещи
DmitriyVintov/java-shareit pull request #1
Opened 2023-09-13 19:42 UTC by DmitriyVintov

2023-09-14 15:35 UTC, z8q requested changes

2023-09-14 15:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NullOrNotBlank
Можно и так.
Но `@NotBlank` проверяет на null тоже

2023-09-14 15:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +@Validated
Если тут удалить `@Validated`, не будет работать?
Обычно применяем, если в контроллере на аргументах есть валидация `@Min`,  `@Max`, `@Size` и т.д.

2023-09-14 15:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        itemRepository.getItems().stream()
Брать целиком списки и итерироватся не очень эффективно.
Тем более, что мы в мапе по ключу можем доставать данные.
Когда базу подключим в следующих домашках, тоже можно будет только одну запись доставать.

В методе search имеет смысл проходить по всему списку, так как внутренние поля сравниваем с text.

2023-09-14 15:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        userRepository.getUsers().stream()
Тут тоже можно пересмотреть поиск.
Если userId известен, в мапе он является ключом. Можно сразу по ключу достать

2023-09-14 15:35 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        checkUserByIdAndEmail(userId, userDto);
Похоже можно сократить до одного чека - checkUserByIdAndEmail

2023-09-14 15:55 UTC, DmitriyVintov commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NullOrNotBlank
Я это знаю. Cмысл аннотации в другом. NotBlank - не null и не пустая строка. NullOrNotBlank - или null, или не пустая строка. С NotBlank тесты не проходят

2023-09-14 15:59 UTC, DmitriyVintov commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +@Validated
Взял из статьи Стручкова https://struchkov.dev/blog/ru/spring-boot-validation/ для групп валидации

2023-09-14 16:16 UTC, DmitriyVintov commented
Изменил методы проверки пользователя и вещи в сервисах. Убрал лишнюю проверку. По остальным замечаниям оставил коментарии

2023-09-15 14:41 UTC, z8q approved these changes

2023-09-18 15:29 UTC, merged